name: CI

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest==8.3.4 pytest-cov==6.0.0 coverage==7.6.1
        pip install -r requirements.txt

    - name: Run tests and Coversage
      run: |
        pytest --cov=. --cov-report=xml
        coverage xml --omit='*test*,*__init__.py'
    
    - name: Pytest coverage comment
      uses: orgoro/coverage@v3.2
      with:
        coverageFile: coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_docker:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t flask:latest -f .docker/Dockerfile .

